/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Proizvodjac;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleProizvodjaci;

/**
 *
 * @author Stefan
 */
public class FormaPIBPro extends javax.swing.JFrame {
    /**
     * Creates new form FormaPretragaPro
     */
    public FormaPIBPro() {
        initComponents();
        btnPonisti.setEnabled(false);
        btnObrisi.setEnabled(false);
        btnIzmena.setEnabled(false);
        srediTabeluInicijalno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFKriterijum = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProizvodjaci = new javax.swing.JTable();
        btnPonisti = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFNaz = new javax.swing.JTextField();
        txtFEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnIzmena = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga, izmena i brisanje proizvođača");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga i brisanje proizvođača"));

        jLabel1.setText("Kriterijum pretrage proizvođača:");

        btnPretraga.setText("Pretraži");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        tblProizvodjaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProizvodjaci);

        btnPonisti.setText("Ponšti filter");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši izabranog proizvođača");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPretraga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPonisti))
                            .addComponent(txtFKriterijum))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnObrisi, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretraga)
                    .addComponent(btnPonisti))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena proizvođača"));

        jLabel2.setText("Unesite novi naziv:");

        jLabel3.setText("Unesite novi email:");

        btnIzmena.setText("Izmena izabranog proizvođača");
        btnIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmenaActionPerformed(evt);
            }
        });

        jLabel4.setText("Izaberite proizvođača u tabeli kako bi ga izmenili:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmena)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFEmail)
                            .addComponent(txtFNaz, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFNaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIzmena)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        String kriterijum = txtFKriterijum.getText();
        if(kriterijum.isEmpty()){
            vratiListuProizvodjaca();
        } else{
            btnPonisti.setEnabled(true);
            vratiListuProZaUslov(kriterijum);
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        txtFKriterijum.setText("");
        vratiListuProizvodjaca();
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ModelTabeleProizvodjaci mtp = (ModelTabeleProizvodjaci) tblProizvodjaci.getModel();
        int red = tblProizvodjaci.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Morate da izaberete proizvođača u tabeli");
            return;
        }
        Proizvodjac p = mtp.vratiProizvodjaca(red);
        Kontroler.getInstanca().obrisiProizvodjaca(p);
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmenaActionPerformed
        if(txtFNaz.getText().isEmpty() && txtFEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Morate popuniti bar jedno polje za izmenu");
            return;
        }
        ModelTabeleProizvodjaci mtp = (ModelTabeleProizvodjaci) tblProizvodjaci.getModel();
        int red = tblProizvodjaci.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Morate da izaberete proizvođača u tabeli");
            return;
        }
        Proizvodjac p = mtp.vratiProizvodjaca(red);
        String naz = txtFNaz.getText();
        if(!naz.isEmpty()){
            p.setNazivProizvodjaca(naz);
        }
        String email = txtFEmail.getText();
        if(!email.isEmpty()){
            if(!email.contains("@")){
            JOptionPane.showMessageDialog(this, "Email mora sadržati @");
            return;
            }
            if(email.startsWith("@") || email.endsWith("@")){
            JOptionPane.showMessageDialog(this, "Email ne sme da počinje ili da se završava sa @");
            return;
            }
            p.setEmailProizvodjaca(email);
        }
        Kontroler.getInstanca().izmeniProizvodjaca(p);
    }//GEN-LAST:event_btnIzmenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPIBPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPIBPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPIBPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPIBPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPIBPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmena;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProizvodjaci;
    private javax.swing.JTextField txtFEmail;
    private javax.swing.JTextField txtFKriterijum;
    private javax.swing.JTextField txtFNaz;
    // End of variables declaration//GEN-END:variables

    private void vratiListuProizvodjaca() {
        Kontroler.getInstanca().vratiSveProizvodjace();
    }

    public void neuspesnoVracanje() {
        JOptionPane.showMessageDialog(this, "Sistem ne može da pronađe proizvođače");
    }

    public void vraceniProizvodjaci(ArrayList<Proizvodjac> sviProizvodjaci) {
        JOptionPane.showMessageDialog(this, "Sistem je vratio sve proizvođače");
        btnPonisti.setEnabled(false);
        srediTabelu(sviProizvodjaci);
    }

    private void srediTabelu(ArrayList<Proizvodjac> lista) {
        ModelTabeleProizvodjaci mtp = new ModelTabeleProizvodjaci(lista);
        tblProizvodjaci.setModel(mtp);
        btnObrisi.setEnabled(true);
        btnIzmena.setEnabled(true);
    }

    private void vratiListuProZaUslov(String kriterijum) {
        Kontroler.getInstanca().vratiProizvodjaceZaUslov(kriterijum);
    }

    public void vraceniProizvodjaciZaUslov(ArrayList<Proizvodjac> listaProizvodjaca) {
        JOptionPane.showMessageDialog(this, "Sistem je pronašao proizvođače po zadatim vrednostima");
        srediTabelu(listaProizvodjaca);
    }

    private void srediTabeluInicijalno() {
        ModelTabeleProizvodjaci mtp = new ModelTabeleProizvodjaci();
        tblProizvodjaci.setModel(mtp);
    }

    public void brisanjeProizvodjaca(String poruka) {
        JOptionPane.showMessageDialog(this, poruka);
        vratiListuProizvodjaca();
    }

    public void izmenaProizvodjaca(String poruka) {
        JOptionPane.showMessageDialog(this, poruka);
        vratiListuProizvodjaca();
    }
}
