/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Komponenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modeli.ModelTabeleKomponente;

/**
 *
 * @author Stefan
 */
public class FormaBrisanjeKomp extends javax.swing.JFrame {
    boolean cekaj = true;
    boolean flag = true;

    /**
     * Creates new form FormaBrisanjeKomp
     */
    public FormaBrisanjeKomp() {
        initComponents();
        btnPonisti.setEnabled(false);
        btnObrisi.setEnabled(false);
        srediTabeluInicijalno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFKriterijum = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKomponente = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Brisanje komponente");

        jLabel1.setText("Kriterijum pretrage komponenti:");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnPonisti.setText("Poništi filter");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        tblKomponente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKomponente);

        btnObrisi.setText("Obriši izabranu komponentu");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPretrazi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPonisti))
                            .addComponent(txtFKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(btnObrisi)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretrazi)
                    .addComponent(btnPonisti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnObrisi)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        cekaj = true;
        String kriterijum = txtFKriterijum.getText();
        if(kriterijum.isEmpty()){
            flag = true;
        } else{
            flag = false;
        }
        Kontroler.getInstanca().vratiKomponente();
        if(!kriterijum.isEmpty()){
            while(cekaj){
                System.out.print("");
            }
            System.out.println("");
            vratiKomponenteUslov(kriterijum);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        txtFKriterijum.setText("");
        flag = true;
        Kontroler.getInstanca().vratiKomponente();
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ModelTabeleKomponente mtk = (ModelTabeleKomponente) tblKomponente.getModel();
        int red = tblKomponente.getSelectedRow();
        if(red == -1){
            JOptionPane.showMessageDialog(this, "Morate da odaberete komponentu iz tabele");
            return;
        }
        Komponenta k = mtk.vratiKomponentu(red);
        Kontroler.getInstanca().obrisiKomponentu(k);
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaBrisanjeKomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaBrisanjeKomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaBrisanjeKomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaBrisanjeKomp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaBrisanjeKomp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKomponente;
    private javax.swing.JTextField txtFKriterijum;
    // End of variables declaration//GEN-END:variables

    private void srediTabeluInicijalno() {
        ModelTabeleKomponente mtk = new ModelTabeleKomponente();
        tblKomponente.setModel(mtk);
    }

    public void neuspesnoVracanjeKomponenti() {
        flag = false;
        JOptionPane.showMessageDialog(this, "Sistem ne može da pronađe komponente po zadatim parametrima");
    }

    public void vraceneKomponente(ArrayList<Komponenta> sveKomponente) {
        if(flag){
            JOptionPane.showMessageDialog(this, "Sistem je vratio sve komponente");
        }
        srediTabelu(sveKomponente);
    }

    private void srediTabelu(ArrayList<Komponenta> lista) {
        ModelTabeleKomponente mtk = new ModelTabeleKomponente(lista);
        tblKomponente.setModel(mtk);
        btnObrisi.setEnabled(true);
        btnPonisti.setEnabled(false);
        cekaj = false;
        flag = false;
    }

    private void vratiKomponenteUslov(String kriterijum) {
        ModelTabeleKomponente mtk = (ModelTabeleKomponente) tblKomponente.getModel();
        ArrayList<Komponenta> lista = mtk.filtriraj(kriterijum);
        cekaj = true;
        if(lista.isEmpty()){
            JOptionPane.showMessageDialog(this, "Sistem ne može da pronađe komponente po zadatim parametrima");
            return;
        }
        JOptionPane.showMessageDialog(this, "Sistem je pronašao komponente po zadatim parametrima");
        btnPonisti.setEnabled(true);
    }

    public void brisanjeKomponente(String poruka) {
        JOptionPane.showMessageDialog(this, poruka);
        txtFKriterijum.setText("");
        flag = true;
        Kontroler.getInstanca().vratiKomponente();
    }
}
